package models;
// Generated Feb 26, 2019 10:47:58 PM by Hibernate Tools 4.3.1



/**
 * SongCatalog generated by hbm2java
 */
public class SongCatalog  implements java.io.Serializable {


    private Integer songId;
    private String songTitle;

    public SongCatalog() {
    }

    public SongCatalog(String songTitle) {
       this.songTitle = songTitle;
    }
   
    public Integer getSongId() {
        return this.songId;
    }
    
    public void setSongId(Integer songId) {
        this.songId = songId;
    }
    public String getSongTitle() {
        return this.songTitle;
    }
    
    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle;
    }

}


